a = int(input('coloque um numero para verificar a sua tabuada '))
b = int(input('coloque outro numero'))
if b < a:
    print('Nenhuma tabuada no intervalo!')
else:
    print('{} x {} = {} '.format(a, 1, a*1))
    print('{} x {} = {} '.format(a, 2, a*2))
    print('{} x {} = {} '.format(a, 3, a*3))
    print('{} x {} = {} '.format(a, 4, a*4))
    print('{} x {} = {} '.format(a, 5, a*5))
    print('{} x {} = {} '.format(a, 6, a*6))
    print('{} x {} = {} '.format(a, 7, a*7))
    print('{} x {} = {} '.format(a, 8, a*8))
    print('{} x {} = {} '.format(a, 9, a*9))
    print('{} x {} = {} '.format(a, 10, a*10))
    print('-' *10)

    print('{} x {} = {} '.format(b, 1, b*1))
    print('{} x {} = {} '.format(b, 2, b*2))
    print('{} x {} = {} '.format(b, 3, b*3))
    print('{} x {} = {} '.format(b, 4, b*4))
    print('{} x {} = {} '.format(b, 5, b*5))
    print('{} x {} = {} '.format(b, 6, b*6))
    print('{} x {} = {} '.format(b, 7, b*7))
    print('{} x {} = {} '.format(b, 8, b*8))
    print('{} x {} = {} '.format(b, 9, b*9))
    print('{} x {} = {} '.format(b, 10, b*10))

    print('-' *10)